---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-terminal
  name: docker-terminal
  namespace: dsdo-system
spec:
  ports:
    - port: 22
      protocol: TCP
      name: ssh
  selector:
    app: docker-terminal
    state: blue
