apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terminal
  labels:
    app: terminal
  namespace: dsdo-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: terminal
        state: blue
    spec:
      containers:
        - name: terminal
          image: ektar/linux-ldap:v1.1.3
          volumeMounts:
          - name: ldap-client-conf
            mountPath: "/etc/sssd/sssd.conf"
            subPath: sssd.conf
          - name: ldap-client-conf
            mountPath: "/etc/ldap.conf"
            subPath: ldap.conf
          - name: ldap-client-conf
            mountPath: "/etc/auth-client-config/profile.d/sss"
            subPath: sss
          - name: nfs-home 
            mountPath: /home/users  
          ports:
            - containerPort: 22
              name: ssh
      volumes:
        - name: ldap-client-conf
          secret:
            secretName: ldap-client-conf
            items:
              - key: sssd.conf
                path: sssd.conf
                mode: 0600
              - key: ldap.conf
                path: ldap.conf
                mode: 0644
              - key: profile.d-sss
                path: sss
                mode: 0644
        - name: nfs-home
          nfs:
            path: /home
            server: {{ org_info['efs_name'] }}
            readOnly: false