apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
      annotations:
        pod.beta.kubernetes.io/hostname: ldap1.default
    spec:
      initContainers:
        - name: init-ldap
          image: ektar/linux-base:1.0
          command: ["mkdir", "-p",
                    "/mnt/efs/system/ldap/config",
                    "/mnt/efs/system/ldap/data",
                    "/mnt/efs/system/ldap/certs"]
          volumeMounts:
            - name: efs-root
              mountPath: /mnt/efs
      containers:
        - name: ldap
          image: ektar/ldap:1.1.9
          args: ["--copy-service"]
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs
            - name: secret-volume
              mountPath: /container/environment/01-custom
            - name: container-run
              mountPath: /container/run
          ports:
            - containerPort: 389
              name: ldap
            - containerPort: 636
              name: ldaps
      volumes:
        - name: ldap-data
          nfs:
            path: /system/ldap/config
            server: fs-6c3ce725.efs.us-east-1.amazonaws.com
            readOnly: false
        - name: ldap-config
          nfs:
            path: /system/ldap/data
            server: fs-6c3ce725.efs.us-east-1.amazonaws.com
            readOnly: false
        - name: ldap-certs
          nfs:
            path: /system/ldap/certs
            server: fs-6c3ce725.efs.us-east-1.amazonaws.com
            readOnly: false
        - name: "secret-volume"
          secret:
            secretName: "ldap-secret"
        - name: efs-root
          nfs:
            path: /
            server: fs-6c3ce725.efs.us-east-1.amazonaws.com
            readOnly: false
        - name: container-run
          emptyDir: {}
