up:
	kubectl apply -f secret.yaml
	kubectl apply -f deployment.yaml
	kubectl apply -f service.yaml

down:
	kubectl delete -f service.yaml
	kubectl delete -f deployment.yaml
	kubectl delete -f secret.yaml
