apiVersion: v1
kind: Pod
metadata:
    name: command-demo
    labels:
        purpose: demonstrate-command
spec:
    containers:
    - name: init-ldap
      image: ektar/linux-base:1.0
      command: ["mkdir", "-p",
                "/mnt/efs/system/ldap/config",
                "/mnt/efs/system/ldap/data",
                "/mnt/efs/system/ldap/certs"]
      volumeMounts:
        - name: efs-root
          mountPath: /mnt/efs
    restartPolicy: Never
    volumes:
    - name: efs-root
      nfs:
        path: /
        server: fs-6c3ce725.efs.us-east-1.amazonaws.com
        readOnly: false
