apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap
spec:
  type: NodePort
  ports:
    - port: 389
      nodePort: 30389
      protocol: TCP
      name: ldap
  selector:
    app: ldap
