apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linux-terminal
  labels:
    app: linux-terminal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: linux-terminal
    spec:
      containers:
        - name: linux-terminal
          image: ektar/linux-ldap:1.0
          ports:
            - containerPort: 22
          volumeMounts:
            - name: nfs-home
              mountPath: /home/users
          ports:
            - containerPort: 22
              name: ssh
      volumes:
        - name: nfs-home
          nfs:
            path: /home
            server: fs-6c3ce725.efs.us-east-1.amazonaws.com
            readOnly: false