apiVersion: v1
kind: Service
metadata:
  labels:
    app: linux-terminal
  name: linux-terminal
spec:
  type: NodePort
  ports:
    - port: 22
      nodePort: 31022
      protocol: TCP
      name: linux-terminal-ssh
  selector:
    app: linux-terminal
