apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ldap-ui
  namespace: ldap
spec:
  tls:
  - hosts:
    - "ldap-ui.internal.{{ org_info['cluster_name'] }}.{{ org_info['domain'] }}"
    secretName: ldap-ui-tls
  rules:
    - host: "ldap-ui.internal.{{ org_info['cluster_name'] }}.{{ org_info['domain'] }}"
      http:
        paths:
        - path: /
          backend:
            serviceName: ldap-ui
            servicePort: 80
