apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ldap-ui
  namespace: ldap
  annotations:
    dns.alpha.kubernetes.io/internal: ldap-ui.internal.kube.ds-do.com
spec:
  rules:
    - host: ldap-ui.internal.kube.ds-do.com
      http:
        paths:
        - path: /ldap-ui
          backend:
            serviceName: ldap-ui
            servicePort: 80
