---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
    state: blue
  name: ldap-tls
  namespace: ldap
  annotations:
    dns.alpha.kubernetes.io/internal: "ldap.internal.{{ org_info['cluster_name'] }}.{{ org_info['domain'] }}"
spec:
  type: NodePort
  ports:
    - port: 389
      name: ldap
    - port: 636
      nodePort: 30636
      protocol: TCP
      name: ldap-tls
  selector:
    app: ldap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
    state: blue
  name: ldap
  namespace: ldap
spec:
  ports:
    - port: 389
      name: ldap
  selector:
    app: ldap
