apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
  namespace: ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      initContainers:
        - name: init-ldap
          image: ektar/linux-base:1.0
          command: ["mkdir", "-p",
                    "/mnt/efs/system/ldap/config",
                    "/mnt/efs/system/ldap/data",
                    "/mnt/efs/system/ldap/certs",
                    "/mnt/efs/system/ldap/iwashere"]
          volumeMounts:
            - name: efs-root
              mountPath: /mnt/efs
      containers:
        - name: ldap
          image: ektar/ldap:1.1.9
          args: ["--copy-service"]
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs
            - name: secret-volume
              mountPath: /container/environment/01-custom
            - name: container-run
              mountPath: /container/run
          ports:
            - containerPort: 389
              name: ldap
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-data
        - name: ldap-certs
          persistentVolumeClaim:
            claimName: ldap-data
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-data
        # - name: "secret-volume"
        #   secret:
        #     secretName: "ldap-secret"
        - name: container-run
          emptyDir: {}
