---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-tls
  namespace: ldap
type: Opaque
data:
  tls.key: "{{ certs['ldap']['key'] }}"
  tls.crt: "{{ certs['ldap']['crt'] }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-ui-tls
  namespace: ldap
type: Opaque
data:
  tls.key: "{{ certs['ldap-ui']['key'] }}"
  tls.crt: "{{ certs['ldap-ui']['crt'] }}"
