apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap-ui
  labels:
    app: ldap-ui
  namespace: ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap-ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dsdo-role
                operator: In
                values:
                - admin-node
      containers:
        - name: ldap-ui
          image: ektar/ldap-ui:v0.7.1
          volumeMounts:
            - name: ldap-ui-certs
              mountPath: /container/service/phpldapadmin/assets/apache2/certs
            - name: ldap-client-certs
              mountPath: /container/service/ldap-client/assets/certs
          args: ["--loglevel", "debug"]
          ports:
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "ldap.ldap"
            - name: PHPLDAPADMIN_SERVER_ADMIN
              value: "{{ org_info['admin_email'] }}"
            - name: PHPLDAPADMIN_SERVER_PATH
              value: "/"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
            - name: PHPLDAPADMIN_TRUST_PROXY_SSL
              value: "true"
            - name: PHPLDAPADMIN_LDAP_CLIENT_TLS
              value: "false"
            - name: PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT
              value: "allow"
            - name: PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME
              value: "ca.crt"
      volumes:
        - name: ldap-ui-certs
          secret:
            secretName: ldap-ui-tls
        - name: ldap-client-certs
          secret:
            secretName: ldap-client-tls
