version: 1.0.0

general:
  organization: "Data Science and DevOps"
  domain: "ds-do.com"
  admin_email: "eric@ds-do.com"

ldap:
  base: "dc=ds-do,dc=com"
  admin_password: "<prompt>"
  readonly_password: "<prompt>"
  config_password: "<prompt>"

initial_users:
- first_name: "User"
  last_name: "One"
  username: "user_one"
  user_id: 
  ssh_key: 
- first_name: "User"
  last_name: "Two"
  username: "user_two"
  user_id: 
  ssh_key: 

kops:
  state_store_name: "dsdo-k8s-state-store-2"
  cluster_name: "kube"

# Notes:
# cluster_name gets appended to general.domain

