version: 1.0.0

general:
  organization: "Data Science and DevOps"
  domain: "ds-do.com"
  admin_email: "eric@ds-do.com"
  lets_encrypt_prefix: "/tmp/le-"
  in_production: "True"
  vpc_id: "vpc-1bae0c63"
  region: "us-east-1"
  efs_subnet_id: "subnet-b0b0459f"
  efs_id: "fs-6c3ce725"

# Notes:
# cluster_name gets appended to general.domain
kops:
  state_store_name: "dsdo-k8s-state-store-2"
  cluster_name: "kube"

ldap:
  base: "dc=ds-do,dc=com"
  initial_users:
  - first_name: "Eric"
    last_name: "Carlson"
    username: "ecarlson"
    user_id: 5100
    ssh_pubkey_file: ~/.ssh/ecarlson.pub
  - first_name: "User"
    last_name: "Two"
    username: "user_two"
    user_id: 5101
    ssh_pubkey_file: ~/.ssh/user_two.pub
  admins:
  - ecarlson
  bastion_access:
  - ecarlson
  shell_access:
  - ecarlson

