apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ldap-ui
spec:
  rules:
    - host: ldap-ui.internal.k8s.ds-do.com
      http:
        paths:
        - path: /
          backend:
            serviceName: ldap-ui
            servicePort: 80