---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bastion
  name: bastion
  namespace: dsdo-system
  annotations:
    dns.alpha.kubernetes.io/external: "ssh.{{ org_info['cluster_name'] }}.{{ org_info['domain'] }}"
spec:
  type: NodePort
  ports:
    - port: 22
      nodePort: 30022
      protocol: TCP
      name: ssh
  selector:
    app: bastion
    state: blue