#cloud-config

repo_update: true
repo_upgrade: all

packages:
 - auth-client-config 
 - awscli 
 - dnsutils 
 - groff
 - iputils-ping 
 - jq 
 - ldap-utils 
 - libldap2-dev 
 - libsasl2-dev 
 - libssl-dev
 - nfs-common 
 - python-dev 
 - python-ldap 
 - python-pip 
 - screen 
 - telnet 
 - tmux 
 - unzip 

