---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub
  namespace: dsdo-system
spec:
  ports:
    - port: 22
      protocol: TCP
      name: ssh
    - port: 8000
      protocol: TCP
      name: jupyterhub
  selector:
    app: jupyterhub
    state: blue