apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{ kops_fqn }}
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{ kops_state_store }}/{{ kops_fqn }}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-{{ region }}
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-{{ region }}
      name: a
    name: events
  externalDns:
    watchIngress: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.{{ kops_fqn }}
  networkCIDR: {{ vpc_cidr }}
  networkID: {{ vpc_id }}
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - id: {{ subnet_id }}
    name: {{ region }}
    type: Public
    zone: {{ region }}
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-11T03:06:19Z
  labels:
    kops.k8s.io/cluster: {{ kops_fqn }}
  name: master-{{ region }}
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  rootVolumeSize: 20
  rootVolumeType: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{ region }}
  role: Master
  subnets:
  - {{ region }}

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-11T03:06:19Z
  labels:
    kops.k8s.io/cluster: {{ kops_fqn }}
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.small
  maxSize: 2
  minSize: 2
  rootVolumeSize: 20
  rootVolumeType: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    dsdo-role: admin-node
  role: Node
  subnets:
  - {{ region }}
